
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
  <TITLE>IVCon technical information</TITLE>
  <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">

<?php
   require_once '../include/basics.php';
   $home_path="../";
   addGlobalHeaderTags();
?>

</HEAD>

<?php
   require_once $home_path.'include/sidebar.php';
?>

<BODY TOPMARGIN=0 LEFTMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0>

<div class="big_hdr" id="titlebar">Technical information</div>

<div id="toplogo"><img <?php echo "src=\"".$home_path."/pictures/ivcon_icon_64.png\""; ?>
 ALT="IVCon logo" TITLE="IVCon logo"/></div>

<?php drawSidebar('sidebar_techinfo','techinfo_files'); ?>

<div id="page_content">

<h3 align="center">
  Reference of IVCon source files:
</h3>
<p><h4>Most importand files:</h4>
<ul>
<li>
  <b>ivconv.h</b> is a header file; it defines IVCON class and many helper structures;
    it also contains #defines for formats supported by the compilation;
</li>
<li>
  <b>ivconv.cpp</b> contains methods definitions for IVCON class; all methods that are not
    format-specific, are stored inside this file;
</li>
<li>
  <b>main.cpp</b> is the main program for converting graphics files; contains INTERACT module;
</li>
<li>
  <b>tmat.h</b> is a header file for tmat.cpp, which defines transformation matrices;
</li>
<li>
  <b>tmat.cpp</b> is a collection of functions for supporting transformation matrices;
</li>
<li>
  <b>utils.cpp</b> is a collection of utilities for IVCON; it contains file reading
    routines and some various functions;
</li>
<li>
  <b>utils.h</b> defines functions in UTILS.CPP, and defines structures like vector,
   vec2 and vec3, used for storing data in whole program;
</li>
</ul></p>

<p><h4>Project files and compilation helpers:</h4>
<ul>
<li><b>Makefile.win</b> windows makefile; automatically generated by Dev-C++</li>
<li><b>Makefile</b> manually written linux makefile;</li>
<li><b>ivcon.ico</b> the program icon</li>
<li><b>ivcon.dev</b> project file for Dev-C++</li>
<li><b>ivcon.layout</b> project layout for Dev-C++</li>
<li><b>ivcon_private.h</b> resource definition for Dev-C++</li>
<li><b>ivcon_private.rc</b> resource definition for Dev-C++</li>
<li><b>ivcon_private.res</b> resource definition for Dev-C++</li>
<li><b>ivcon.dsp</b> project file for Microsoft Developer Studio</li>
<li><b>ivcon.dsw</b> project workspace for Microsoft Developer Studio</li>
<li><b>ivcon.ncb</b> Microsoft C/C++ program database</li>
<li><b>ivcon.opt</b> Microsoft OPT workspace file</li>
<li><b>ivconexe.dsp</b> project file for Microsoft Developer Studio</li>
<li><b>ivconexe.dsw</b> project workspace for Microsoft Developer Studio</li>
<li><b>ivconexe.ncb</b> Microsoft C/C++ program database</li>
<li><b>ivconexe.opt</b> Microsoft OPT workspace file</li>
</ul></p>

<p><h4>Format-specific files:</h4>
<ul>
<li><b>tds.cpp</b> 3DS format support functions</li>
<li><b>ofile.h</b> 3DS format support header</li>
<li><b>asc.cpp</b> ASC format support functions</li>
<li><b>ase.cpp</b> ASE format support functions</li>
<li><b>byu.cpp</b> BYU format support functions</li>
<li><b>dxf.cpp</b> DXF format support functions</li>
<li><b>gmod.cpp</b> GMOD format support functions</li>
<li><b>hrc.cpp</b> HRC format support functions</li>
<li><b>iv.cpp</b> IV format support functions</li>
<li><b>obj.cpp</b> OBJ format support functions</li>
<li><b>pov.cpp</b> POV format support functions</li>
<li><b>smf.cpp</b> SMF format support functions</li>
<li><b>stl.cpp</b> STL format support functions</li>
<li><b>swm.cpp</b> SWM format support functions</li>
<li><b>sw_maprd.cpp</b> SWM format support functions</li>
<li><b>sw_maprd.h</b> SWM format support header</li>
<li><b>swv.cpp</b> SWV format support functions</li>
<li><b>sw_vehrd.cpp</b> SWV format support functions</li>
<li><b>sw_vehrd.h</b> SWV format support header</li>
<li><b>tec.cpp</b> TEC format support functions</li>
<li><b>tri.cpp</b> TRI format support functions</li>
<li><b>txt.cpp</b> TXT format support functions</li>
<li><b>ucd.cpp</b> UCD format support functions</li>
<li><b>vla.cpp</b> VLA format support functions</li>
<li><b>wrl.cpp</b> WRL format support functions</li>
<li><b>xgl.cpp</b> XGL format support functions</li>
</ul></p>

<hr>
<?php addGlobalFooterTags(); ?>

</div>

<BR>

</BODY>
</HTML>
